In [1]:
import pandas as pd

In [10]:
df = pd.read_csv("brainsize.txt", sep="\t", na_values=['NA'])

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Gender     40 non-null     str
 1   FSIQ       40 non-null     int64
 2   VIQ        40 non-null     int64
 3   PIQ        40 non-null     int64
 4   Weight     38 non-null     float64
 5   Height     39 non-null     float64
 6   MRI_Count  40 non-null     int64
dtypes: float64(2), int64(4), str(1)
memory usage: 2.3 KB

In [12]:
df.columns.tolist()

['Gender', 'FSIQ', 'VIQ', 'PIQ', 'Weight', 'Height', 'MRI_Count']

In [15]:
df.columns.tolist()[1:-1]

['FSIQ', 'VIQ', 'PIQ', 'Weight', 'Height']

In [21]:
params = df.columns.tolist()[1:-1]
df1 = pd.DataFrame({
'Male':   [0.0]*len(params),
    'Female': [0.0]*len(params)
}, index=params)
df1

        Male  Female
FSIQ     0.0     0.0
VIQ      0.0     0.0
PIQ      0.0     0.0
Weight   0.0     0.0
Height   0.0     0.0

In [31]:
df1["Male"].sort_values().head(1).index[0]

'FSIQ'

In [38]:
df1.loc["FSIQ", "Male"] = 2.5
df1["Male"]["FSIQ"]

np.float64(2.5)

In [54]:
params = df.columns.tolist()[1:-1]
cor_df = pd.DataFrame(index=params, columns=['Male', 'Female'])
cor_df

       Male Female
FSIQ    NaN    NaN
VIQ     NaN    NaN
PIQ     NaN    NaN
Weight  NaN    NaN
Height  NaN    NaN

In [43]:
male_data = df[df['Gender'] == 'Male']
female_data = df[df['Gender'] == 'Female']

In [57]:
params = df.columns.tolist()[1:-1]
cor_df = pd.DataFrame(index=params, columns=['Male', 'Female'])

male_data = df[df['Gender'] == 'Male']
female_data = df[df['Gender'] == 'Female']

for p in params:
    cor_df.loc[p, 'Male'] = male_data[p].corr(male_data['MRI_Count'])
    cor_df.loc[p, 'Female'] = female_data[p].corr(female_data['MRI_Count'])

In [58]:
cor_df

            Male    Female
FSIQ    0.498369  0.325697
VIQ     0.413105  0.254933
PIQ     0.568237  0.396157
Weight -0.076875  0.446271
Height  0.301543  0.174541

In [60]:
cor_df['Female'].to_dict()

{'FSIQ': 0.32569670049637045,
 'VIQ': 0.25493285296147666,
 'PIQ': 0.3961571668684764,
 'Weight': 0.44627135266164303,
 'Height': 0.17454104728809816}

In [71]:
cor_df.abs()

            Male    Female
FSIQ    0.498369  0.325697
VIQ     0.413105  0.254933
PIQ     0.568237  0.396157
Weight  0.076875  0.446271
Height  0.301543  0.174541

In [75]:
cor_df.idxmax()

Male         PIQ
Female    Weight
dtype: str

In [76]:
cor_df.stack()

FSIQ    Male      0.498369
        Female    0.325697
VIQ     Male      0.413105
        Female    0.254933
PIQ     Male      0.568237
        Female    0.396157
Weight  Male     -0.076875
        Female    0.446271
Height  Male      0.301543
        Female    0.174541
dtype: object

In [79]:
cor_df.abs().stack().idxmax()

('PIQ', 'Male')

In [82]:
len(male_data)

20